apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhnj9475.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqlpass
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqlserver
          - name: DB_NAME
            value: "mydrivingDB"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-svc
  labels:
    run: poi
  namespace: api-dev
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: poi