apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registryhnj9475.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqlpass
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlaccess
                key: sqlserver
          - name: DB_NAME
            value: "mydrivingDB"
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "api-kv-dbaccess"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-svc
  labels:
    run: user-java
  namespace: api-dev
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: user-java