# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ingress-cert
  namespace: ingress-controller
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-cert
    type: kubernetes.io/tls
    data:
    - key: tls.key
      objectName: poc-dr-ingress
    - key: tls.crt
      objectName: poc-dr-ingress
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: ""  # Set the clientID of the user-assigned managed identity to use
    keyvaultName:         # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: sqluser
          objectType: secret
    tenantId: 