kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-to-api-dev
  namespace: api-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  namespace: api-dev
  name: apidev@msftopenhack7017ops.onmicrosoft.com