kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-to-web-dev
  namespace: web-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
subjects:
- kind: User
  namespace: web-dev
  name: apidev@msftopenhack7017ops.onmicrosoft.com